### curricurum - 【AIコース】強化学習　入門編1 Q-learning

In [1]:
import gym
# Read gym docs at: https://gym.openai.com/docs/

In [2]:
# use CartPole-v0
env = gym.make("CartPole-v0")

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t + 1))
            break

[-0.03780796 -0.03021378  0.01918507 -0.02968248]
[-0.03841223 -0.22560553  0.01859142  0.26899127]
[-0.04292434 -0.03075376  0.02397125 -0.01777031]
[-0.04353942  0.16401636  0.02361584 -0.30279468]
[-0.04025909 -0.03143406  0.01755995 -0.00275838]
[-0.04088777  0.16343171  0.01750478 -0.28984962]
[-0.03761914  0.35829974  0.01170779 -0.57696073]
[-3.04531451e-02  5.53255642e-01  1.68571081e-04 -8.65932537e-01]
[-0.01938803  0.7483753  -0.01715008 -1.15856246]
[-0.00442053  0.9437165  -0.04032133 -1.45657304]
[ 0.0144538   1.1393094  -0.06945279 -1.76157519]
[ 0.03723999  1.3351451  -0.10468429 -2.07502324]
[ 0.06394289  1.14122951 -0.14618476 -1.81646321]
[ 0.08676748  0.94800541 -0.18251402 -1.57254385]
Episode finished after 14 timesteps
[-0.03793612  0.03540008  0.03307687  0.03991564]
[-0.03722812 -0.16018019  0.03387519  0.34284841]
[-0.04043172 -0.35576729  0.04073216  0.64601814]
[-0.04754706 -0.55143243  0.05365252  0.95124436]
[-0.05857571 -0.74723382  0.07267741  1.26029009

In [4]:
print(env.action_space)

Discrete(2)


In [5]:
print(env.observation_space)

Box(4,)


FrozenLake-v0: https://gym.openai.com/envs/FrozenLake-v0/  

The agent controls the movement of a character in a grid world.   
Some tiles of the grid are walkable, and others lead to the agent falling into the water.   
Additionally, the movement direction of the agent is uncertain and only partially depends on the chosen direction.   
The agent is rewarded for finding a walkable path to a goal tile.

In [6]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt

env = gym.make("FrozenLake-v0")

In [7]:
num_episodes = 1000
Q = np.random.uniform(0, 1, (16, 4))
l = 0.7
gamma = 0.99
rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j += 1
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1. / (i + 1)))
        s1, r, d, _ = env.step(a)
        Q[s, a] = Q[s, a] + l * (r + gamma * np.max(Q[s1, :]) - Q[s, a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

print("Score over time:" + str(sum(rList) / num_episodes))
print("action value table is :")
print(Q)

Score over time:0.001
action value table is :
[[0.27273421 0.75526981 0.83541777 0.75505887]
 [0.77502832 0.84495815 0.72038371 0.781596  ]
 [0.8357468  0.30817351 0.77680343 0.20810837]
 [0.27275254 0.05145128 0.36613807 0.77557096]
 [0.73654864 0.74385535 0.70860905 0.84962643]
 [0.84633828 0.86033589 0.02638715 0.70808269]
 [0.56159731 0.20447442 0.36200345 0.90216501]
 [0.06359537 0.93646165 0.14628155 0.72844657]
 [0.4254317  0.69156493 0.57270153 0.17125585]
 [0.17082956 0.74845056 0.78374791 0.36617423]
 [0.36355483 0.05604861 0.47933015 0.82288412]
 [0.34859354 0.09365059 0.23141162 0.20139876]
 [0.31043519 0.69197417 0.38322659 0.22915102]
 [0.49330934 0.05068056 0.84539246 0.32583936]
 [0.65392606 1.39094342 0.72376015 0.68839728]
 [0.97031025 0.11048217 0.85300267 0.59179321]]
