### カリキュラム - 【AIコース】教師なし学習　Feature Selection 2 filter method

In [1]:
import numpy as np
import pandas as pd
#参加者の名前（aさんからjさん）
name = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h','i','j']
#入校した＝１、入校しなかった＝０
y=np.array([1, 1, 0, 1, 0, 1, 0, 1, 1, 0])
#質問１　今日の説明会は良かった
no1=np.array([4, 4, 2, 4, 0, 2, 1, 3, 2, 0])
#質問２　スクールに魅力を感じた
no2=np.array([3, 4, 1, 3, 0, 3, 1, 4, 4, 0])
#質問３　今日の夕飯は焼肉が食べたい
no3=np.array([2, 0, 3, 1, 2, 4, 0, 4, 1, 0])
#以下質問４〜２０
no4=np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
no5=np.array([0, 2, 2, 1, 1, 0, 3, 0, 0, 3])
no6=np.array([4, 3, 2, 1, 3, 0, 3, 2, 1, 4])
no7=np.array([2, 1, 2, 3, 2, 4, 2, 0, 0, 2])
no8=np.array([2, 0, 0, 2, 4, 3, 4, 3, 0, 3])
no9=np.array([2, 2, 4, 3, 3, 2, 0, 3, 3, 3])
no10=np.array([4, 3, 3, 1, 0, 2, 0, 3, 1, 2])
no11=np.array([3, 4, 4, 4, 1, 3, 1, 1, 3, 2])
no12=np.array([2, 4, 2, 0, 3, 3, 0, 1, 0, 1])
no13=np.array([0, 1, 3, 2, 4, 0, 3, 1, 0, 3])
no14=np.array([4, 3, 4, 4, 4, 4, 4, 4, 4, 4])
no15=np.array([2, 1, 0, 0, 3, 3, 3, 2, 2, 2])
no16=np.array([3, 4, 0, 0, 2, 1, 2, 4, 0, 1])
no17=np.array([2, 3, 0, 3, 0, 2, 0, 3, 4, 0])
no18=np.array([1, 2, 1, 2, 2, 1, 3, 4, 2, 0])
no19=np.array([1, 1, 4, 0, 3, 3, 4, 1, 0, 3])
no20=np.array([0, 1, 0, 0, 0, 3, 1, 2, 3, 3])
X=np.array([no1,no2,no3,no4,no5,no6,no7,no8,no9,no10,no11,no12,no13,no14,no15,no16,no17,no18,no19,no20]).T
variables = [str(i) for i in range(1,21)]
df = pd.DataFrame(X, columns=variables, index=name)
df # jupyter notebookでの実行をお願いします

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20
a  4  3  2  0  0  4  2  2  2   4   3   2   0   4   2   3   2   1   1   0
b  4  4  0  0  2  3  1  0  2   3   4   4   1   3   1   4   3   2   1   1
c  2  1  3  0  2  2  2  0  4   3   4   2   3   4   0   0   0   1   4   0
d  4  3  1  0  1  1  3  2  3   1   4   0   2   4   0   0   3   2   0   0
e  0  0  2  0  1  3  2  4  3   0   1   3   4   4   3   2   0   2   3   0
f  2  3  4  0  0  0  4  3  2   2   3   3   0   4   3   1   2   1   3   3
g  1  1  0  0  3  3  2  4  0   0   1   0   3   4   3   2   0   3   4   1
h  3  4  4  0  0  2  0  3  3   3   1   1   1   4   2   4   3   4   1   2
i  2  4  1  0  0  1  0  0  3   1   3   0   0   4   2   0   4   2   0   3
j  0  0  0  0  3  4  2  3  3   2   2   1   3   4   2   1   0   0   3   3

In [2]:
variables

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20']

In [27]:
from sklearn.feature_selection import VarianceThreshold
x = df.values
vt = 0.2
sel = VarianceThreshold(threshold = vt)
x_after_vt = sel.fit_transform(x)

In [28]:
print(x.shape)
print(x)

(10, 20)
[[4 3 2 0 0 4 2 2 2 4 3 2 0 4 2 3 2 1 1 0]
 [4 4 0 0 2 3 1 0 2 3 4 4 1 3 1 4 3 2 1 1]
 [2 1 3 0 2 2 2 0 4 3 4 2 3 4 0 0 0 1 4 0]
 [4 3 1 0 1 1 3 2 3 1 4 0 2 4 0 0 3 2 0 0]
 [0 0 2 0 1 3 2 4 3 0 1 3 4 4 3 2 0 2 3 0]
 [2 3 4 0 0 0 4 3 2 2 3 3 0 4 3 1 2 1 3 3]
 [1 1 0 0 3 3 2 4 0 0 1 0 3 4 3 2 0 3 4 1]
 [3 4 4 0 0 2 0 3 3 3 1 1 1 4 2 4 3 4 1 2]
 [2 4 1 0 0 1 0 0 3 1 3 0 0 4 2 0 4 2 0 3]
 [0 0 0 0 3 4 2 3 3 2 2 1 3 4 2 1 0 0 3 3]]


In [29]:
print(x_after_vt.shape)
print(x_after_vt)

(10, 18)
[[4 3 2 0 4 2 2 2 4 3 2 0 2 3 2 1 1 0]
 [4 4 0 2 3 1 0 2 3 4 4 1 1 4 3 2 1 1]
 [2 1 3 2 2 2 0 4 3 4 2 3 0 0 0 1 4 0]
 [4 3 1 1 1 3 2 3 1 4 0 2 0 0 3 2 0 0]
 [0 0 2 1 3 2 4 3 0 1 3 4 3 2 0 2 3 0]
 [2 3 4 0 0 4 3 2 2 3 3 0 3 1 2 1 3 3]
 [1 1 0 3 3 2 4 0 0 1 0 3 3 2 0 3 4 1]
 [3 4 4 0 2 0 3 3 3 1 1 1 2 4 3 4 1 2]
 [2 4 1 0 1 0 0 3 1 3 0 0 2 0 4 2 0 3]
 [0 0 0 3 4 2 3 3 2 2 1 3 2 1 0 0 3 3]]


In [30]:
variables = np.array(variables)
variables[sel.variances_ < vt]

array(['4', '14'],
      dtype='<U2')

In [31]:
def variance(x):
    var = np.sum((x - np.mean(x)) ** 2) / len(x)
    return var

In [32]:
print(np.var(x, axis = 0))

[ 2.16  2.41  2.21  0.    1.36  1.61  1.36  2.29  1.05  1.69  1.44  1.84
  2.01  0.09  1.16  2.21  2.21  1.16  2.2   1.61]


In [34]:
# SelectKBest
from sklearn.feature_selection import VarianceThreshold, SelectKBest
vt = VarianceThreshold(threshold = 0)
x_vt = vt.fit_transform(x)
print(x_vt.shape)

(10, 19)


In [35]:
variables = np.array(variables)
var_vt = variables[vt.variances_ > 0]
print(var_vt)

['1' '2' '3' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16' '17'
 '18' '19' '20']


In [36]:
N_features = 16
skb = SelectKBest(k = N_features)
x_after_skb = skb.fit_transform(x_vt, y)
x_after_skb.shape

(10, 16)

In [37]:
from sklearn.feature_selection import f_classif
skb = SelectKBest(score_func = f_classif, k = N_features)
x_after_skb = skb.fit_transform(x_vt, y)

In [38]:
idx = np.argsort(skb.scores_)[::-1]
print(idx)

[ 1 15 11 17  0  3  4  9  8  6 12 14  2 16 18 13  5 10  7]


In [40]:
variables[15]

'16'

In [42]:
r = len(var_vt) - N_features
print(var_vt[idx][-r:])

['7' '12' '9']


In [43]:
from sklearn.feature_selection import chi2
skb_chi2 = SelectKBest(score_func = chi2, k = N_features)
x_after_skb_chi2 = skb_chi2.fit_transform(x_vt, y)

idx_chi2 = np.argsort(skb_chi2.scores_)[::-1]
print(var_vt[idx_chi2][-r:])

['12' '14' '9']


In [46]:
def variance_for_selectKBest(x, y):
    var = np.sum((x - np.mean(x, axis = 0)) ** 2, axis = 0) / len(x)
    return var

In [48]:
skb_var = SelectKBest(score_func = variance_for_selectKBest, k = N_features)
x_after_skb_var = skb_var.fit_transform(x_vt, y)
idx_var = np.argsort(skb_var.scores_)[::-1]
print(var_vt[idx_var][-r:])

['15' '9' '14']


In [50]:
# SelectPercentile
from sklearn.feature_selection import SelectPercentile
sp = SelectPercentile(percentile = 50)
x_after_sp = sp.fit_transform(x_vt, y)

In [51]:
from sklearn.feature_selection import SelectPercentile
sp = SelectPercentile(percentile = 84)
x_after_sp = sp.fit_transform(x_vt, y)